name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Environment'
        options: 
        - Stage
        - Prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment..."